apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-zeebe
spec:
  type: bindings.zeebe.command
  version: v1
  metadata:
  - name: gatewayAddr
    value: localhost:26500
  - name: gatewayKeepAlive
    value: 45s
  - name: usePlainTextConnection
    value: true
